apiVersion: v1
kind: Pod
metadata:
  name: kubesec-demo
  labels:
    app: kubesec-demo
    version: v1.0
  annotations:
    description: "Demo pod for kubesec testing"
spec:
  containers:
  - name: kubesec-demo
    image: gcr.io/google-samples/node-hello:1.0
    ports:
    - containerPort: 8080
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "8080"
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: tmp-volume
    emptyDir: {}
  restartPolicy: Always
  serviceAccountName: default
