apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp-production

namespace: webapp-prod

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

resources:
- hpa.yaml
- networkpolicy.yaml

replicas:
- name: webapp
  count: 3

images:
- name: nginx
  newTag: 1.21-alpine
