apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp
data:
  app.properties: |
    app.name=Simple WebApp
    app.version=1.0.0
    app.environment=base
    
    # Database configuration
    database.host=localhost
    database.port=5432
    database.name=webapp_db
    
    # Cache configuration
    cache.enabled=true
    cache.ttl=3600
  
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      
      sendfile on;
      keepalive_timeout 65;
      
      server {
        listen 8080;
        server_name localhost;
        
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        
        location /health {
          access_log off;
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }
      }
    }
